### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by Heyter** [MysteryPancake/GMod-Binding#1]
Where take module( "bind" ) ?

**Comment by MysteryPancake** [comment]
I think it should work if you put it in lua/autorun/client

**Comment by MysteryPancake** [comment]
If that doesn't work, try putting it in lua/includes/modules

**Comment by MysteryPancake** [comment]
Tell me if you can't get it to work

**Comment by Heyter** [comment]
Yep, working.
Close issue.
