### ISSUE TITLE
trying to make weapon switch binds with new format

### ISSUE THREAD

**Issue by pvprangergod** [MysteryPancake/GMod-Binding#2]
my binds are like this
bind.Add( KEY_5, "gravitybind", function()
	Entity( 1 ):SelectWeapon( "weapon_physcannon" )
end )
but dont seem to work
how do i make binds for switching to a weapon?

**Comment by MysteryPancake** [comment]
This script only works clientside. SelectWeapon is serverside. Try using [numpad.OnDown](http://wiki.garrysmod.com/page/numpad/OnDown). I'll post an example soon.

**Comment by MysteryPancake** [comment]
This should work serverside, it does for me:
```
numpad.Register( "gravitybind", function( ply )
	ply:SelectWeapon( "weapon_physcannon" )
end )

numpad.OnDown( Entity( 1 ), KEY_5, "gravitybind" )
```
Sorry, I need to add a disclaimer.

**Comment by MysteryPancake** [comment]
I added a disclaimer:

> It only works client-side, since on serverside you can use the numpad library.

Tell me if the code above fixes the issue.

**Comment by MysteryPancake** [comment]
I think I'll close it now. The above code works for me.
