### ISSUE TITLE
License

### ISSUE THREAD

**Issue by saibotk** [MysteryPancake/GMod-Binding#3]
Hey, this is a cool little snippet, id like to use and i would be grateful, if you could add a license to your project, so people like me know what we are allowed to do with this project and how.

Thanks ;)

**Comment by MysteryPancake** [comment]
I don't usually add a licence for things like this because I want people to be able to steal and copy them for whatever they want. In the readme it says:

> Use it for whatever you want, and have fun!

It's a very small snippet. What's a good license to use?

**Comment by MysteryPancake** [comment]
I added the Unlicense since it seems to be good. If this is a bad license please tell me.
